apiVersion: v2
name: matrix-meetings
description: A helper chart to deploy both the widget and the bot
type: application
version: 0.3.0
appVersion: "0.0.0"
home: https://github.com/nordeck/matrix-meetings
dependencies:
  - name: matrix-calendar-widget
    version: "*"
    repository: "file://../matrix-calendar-widget"
  - name: matrix-calendar-server
    version: "*"
    repository: "file://../matrix-calendar-server"
